CREATE DATABASE IF NOT EXISTS adega_controle;

Use adega_controle;

CREATE TABLE IF NOT EXISTS
produtos (
id INT AUTO_INCREMENT PRIMARY KEY, 
nome VARCHAR(100) NOT NULL, 
categoria VARCHAR(50) NOT NULL,
unidade VARCHAR(50) NOT NULL,
preco DECIMAL(10,2) DEFAULT 0.00,
quantidade INT DEFAULT 0,
data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);